apiVersion: v1
kind: Pod
metadata:
  name: quota-positive
spec:
  restartPolicy: Never
  securityContext:
    runAsUser: 1000
    runAsNonRoot: true
  containers:
  - name: client
    image: s3client:v1
    imagePullPolicy: IfNotPresent
    command: ["sleep", "10"]
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop: [ALL]
      seccompProfile:
        type: RuntimeDefault
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
